openapi: 3.0.3
info:
  title: Ecommerce API
  version: 0.0.0
paths:
  /api/user:
    get:
      operationId: api_user_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BaseUser'
          description: ''
    post:
      operationId: api_user_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BaseUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BaseUser'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseUser'
          description: ''
  /api/user/{id}/:
    get:
      operationId: api_user_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseUser'
          description: ''
    put:
      operationId: api_user_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BaseUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BaseUser'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseUser'
          description: ''
    patch:
      operationId: api_user_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBaseUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBaseUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBaseUser'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseUser'
          description: ''
components:
  schemas:
    BaseUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          title: Email_address
          maxLength: 254
        username:
          type: string
          maxLength: 300
        firstname:
          type: string
          maxLength: 300
        password1:
          type: string
          writeOnly: true
        password2:
          type: string
          writeOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
      required:
      - created
      - email
      - id
      - password1
      - password2
      - updated
      - username
    PatchedBaseUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          title: Email_address
          maxLength: 254
        username:
          type: string
          maxLength: 300
        firstname:
          type: string
          maxLength: 300
        password1:
          type: string
          writeOnly: true
        password2:
          type: string
          writeOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
