# Generated by Django 4.2.3 on 2024-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
