# Generated by Django 4.2.3 on 2024-03-03 19:53

from django.db import migrations, models
import django.db.models.manager
import django_resized.forms
import ecommerce.utils.media


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_baseuser_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseuser",
            options={
                "base_manager_name": "prefetch_manager",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelManagers(
            name="baseuser",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name="baseuser",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="baseuser",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="baseuser",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="/download (11).png/",
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                upload_to=ecommerce.utils.media.MediaHelper.get_image_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
