# Generated by Django 4.2.3 on 2024-02-22 07:36

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddressbook",
            name="user",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="productwishlist",
            name="product",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.product"),
        ),
        migrations.AddField(
            model_name="productwishlist",
            name="user",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="productreview",
            name="product",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.product"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="user",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="store.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="myproductattribute",
            name="color",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.color"),
        ),
        migrations.AddField(
            model_name="myproductattribute",
            name="products",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.product"),
        ),
        migrations.AddField(
            model_name="myproductattribute",
            name="size",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.size"),
        ),
        migrations.AddField(
            model_name="images",
            name="products",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.product"),
        ),
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="store.category",
            ),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="order",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.cartorder"),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="user",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
